
---

name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Check lockfile consistency
        run: npm install --package-lock-only --dry-run

      - name: Install UI dependencies
        working-directory: ui
        run: npm ci

      - name: Lint UI
        working-directory: ui
        run: npm run lint

      - name: Test UI
        working-directory: ui
        run: npm test

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Format check
        run: cargo fmt -- --check

      - name: Lint Rust
        run: cargo clippy -- -D warnings

      - name: Run Rust tests
        run: cargo test

